### ISSUE TITLE
Example1 error- is the version 1.0.7 available yet?

### ISSUE THREAD

**Issue by timhockswender** [salvadorgarciamunoz/kipet#173]
Attempting to run in JupyterLab.
Ex 1 saas at end:
AttributeError: 'ReactionModel' object has no attribute 'results'?
Any ideas why?

**Comment by timhockswender** [comment]
I just discovered that example 1 works from command line.

**Comment by timhockswender** [comment]
Still not from jupyterlab. Also I needed to create a template folder in the site package. The install didn’t seem to do this b

**Comment by kwmcbride** [comment]
I am working on updating KIPET to version 1.0.7, which should be ready within the next two weeks. There were several issues found with 1.0.6 regarding the report method (including the template folder creation you mentioned). I would suggest not using that at the moment, but unfortunately all of the examples use this method in the end. In the upcoming version, the report method works as expected.

In response to your JupyterLab issue, did you create a new kernel using a KIPET environment? Were the other methods working before the "results not found" error?

**Comment by timhockswender** [comment]
Thanks. I have not used an environment for KIPET. I will redo my workspace when the update is available. I have discovered in roaming through the example and learn-kikpet examples that various data files need to be loaded but they are never where the py file or Jupyter notebook is looking. I cant yet figure how to to edit. A nice feature would be a reference to a specific file location. This could be permanently set in install but preferably with an option to edit the file to where ever the data is. This is helpful if I am using my own project  data. Regards, Tim
